#!/usr/bin/env python3

import random
import string
import uuid

def random_string(n=16):
	_string = ''.join([random.choice(string.ascii_lowercase + string.digits) for _n in range(n)])
	return _string

def random_password_deprecated():
	lowers = ''.join([random.choice(string.ascii_lowercase) for _n in range(5)])
	uppers = ''.join([random.choice(string.ascii_uppercase) for _n in range(3)])
	numbers = ''.join([random.choice(string.digits) for _n in range(1)])
	symbols = ''.join([random.choice('#/%!?') for _n in range(1)])
	_l = list(lowers + uppers + numbers + symbols)
	random.shuffle(_l)
	return ''.join(_l)

def random_md5():
	return ''.join([random.choice(string.hexdigits.lower()) for _ in range(32)])

def random_sha256():
	return ''.join([random.choice(string.hexdigits.lower()) for _ in range(64)])

def random_sha512():
	return ''.join([random.choice(string.hexdigits.lower()) for _ in range(128)])

def random_uuid():
	return str(uuid.uuid5(uuid.uuid4(),random_md5()))

def random_password(n=12):
	if n < 8:
		n = 12
		symbols_n = 1
		numbers_n = 2
		uppers_n = 2
		lowers_n = 7
	else:
		symbols_n = 1
		numbers_n = 2
		uppers_n = int( n / 4)
		lowers_n = n - uppers_n - 3
	lowers = ''.join([random.choice(string.ascii_lowercase) for _ in range(lowers_n)])
	uppers = ''.join([random.choice(string.ascii_uppercase) for _n in range(uppers_n)])
	numbers = ''.join([random.choice(string.digits) for _n in range(numbers_n)])
	symbols = ''.join([random.choice('#/%!?') for _n in range(symbols_n)])
	_l = list(lowers + uppers + numbers + symbols)
	random.shuffle(_l)
	return ''.join(_l)


def dicom_patient_id():
	return str(random.randint(2022030001, 2022039999))

def dicom_series_number():
	return str(random.randint(30001, 39999))

def person_name():
	first_name = [
    "admiring",
    "adoring",
    "affectionate",
    "agitated",
    "amazing",
    "angry",
    "awesome",
    "beautiful",
    "blissful",
    "bold",
    "boring",
    "brave",
    "busy",
    "charming",
    "clever",
    "cool",
    "compassionate",
    "competent",
    "condescending",
    "confident",
    "cranky",
    "crazy",
    "dazzling",
    "determined",
    "distracted",
    "dreamy",
    "eager",
    "ecstatic",
    "elastic",
    "elated",
    "elegant",
    "eloquent",
    "epic",
    "exciting",
    "fervent",
    "festive",
    "flamboyant",
    "focused",
    "friendly",
    "frosty",
    "funny",
    "gallant",
    "gifted",
    "goofy",
    "gracious",
    "great",
    "happy",
    "hardcore",
    "heuristic",
    "hopeful",
    "hungry",
    "infallible",
    "inspiring",
    "interesting",
    "intelligent",
    "jolly",
    "jovial",
    "keen",
    "kind",
    "laughing",
    "loving",
    "lucid",
    "magical",
    "mystifying",
    "modest",
    "musing",
    "naughty",
    "nervous",
    "nice",
    "nifty",
    "nostalgic",
    "objective",
    "optimistic",
    "peaceful",
    "pedantic",
    "pensive",
    "practical",
    "priceless",
    "quirky",
    "quizzical",
    "recursing",
    "relaxed",
    "reverent",
    "romantic",
    "sad",
    "serene",
    "sharp",
    "silly",
    "sleepy",
    "stoic",
    "strange",
    "stupefied",
    "suspicious",
    "sweet",
    "tender",
    "thirsty",
    "trusting",
    "unruffled",
    "upbeat",
    "vibrant",
    "vigilant",
    "vigorous",
    "wizardly",
    "wonderful",
    "xenodochial",
    "youthful",
    "zealous",
    "zen"
	]
	last_name = [
		"agnesi",
	"albattani",
	"allen",
	"almeida",
	"antonelli",
	"archimedes",
	"ardinghelli",
	"aryabhata",
	"austin",
	"babbage",
	"banach",
	"banzai",
	"bardeen",
	"bartik",
	"bassi",
	"beaver",
	"bell",
	"benz",
	"bhabha",
	"bhaskara",
	"black",
	"blackburn",
	"blackwell",
	"bohr",
	"booth",
	"borg",
	"bose",
	"bouman",
	"boyd",
	"brahmagupta",
	"brattain",
	"brown",
	"buck",
	"burnell",
	"cannon",
	"carson",
	"cartwright",
	"carver",
	"cerf",
	"chandrasekhar",
	"chaplygin",
	"chatelet",
	"chatterjee",
	"chaum",
	"chebyshev",
	"clarke",
	"cohen",
	"colden",
	"cori",
	"cray",
	"curran",
	"curie",
	"darwin",
	"davinci",
	"dewdney",
	"dhawan",
	"diffie",
	"dijkstra",
	"dirac",
	"driscoll",
	"dubinsky",
	"easley",
	"edison",
	"einstein",
	"elbakyan",
	"elgamal",
	"elion",
	"ellis",
	"engelbart",
	"euclid",
	"euler",
	"faraday",
	"feistel",
	"fermat",
	"fermi",
	"feynman",
	"franklin",
	"gagarin",
	"galileo",
	"galois",
	"ganguly",
	"gates",
	"gauss",
	"germain",
	"goldberg",
	"goldstine",
	"goldwasser",
	"golick",
	"goodall",
	"gould",
	"greider",
	"grothendieck",
	"haibt",
	"hamilton",
	"haslett",
	"hawking",
	"hellman",
	"heisenberg",
	"hermann",
	"herschel",
	"hertz",
	"heyrovsky",
	"hodgkin",
	"hofstadter",
	"hoover",
	"hopper",
	"hugle",
	"hypatia",
	"ishizaka",
	"jackson",
	"jang",
	"jemison",
	"jennings",
	"jepsen",
	"johnson",
	"joliot",
	"jones",
	"kalam",
	"kapitsa",
	"kare",
	"keldysh",
	"keller",
	"kepler",
	"khayyam",
	"khorana",
	"kilby",
	"kirch",
	"knuth",
	"kowalevski",
	"lalande",
	"lamarr",
	"lamport",
	"leakey",
	"leavitt",
	"lederberg",
	"lehmann",
	"lewin",
	"lichterman",
	"liskov",
	"lovelace",
	"lumiere",
	"mahavira",
	"margulis",
	"matsumoto",
	"maxwell",
	"mayer",
	"mccarthy",
	"mcclintock",
	"mclaren",
	"mclean",
	"mcnulty",
	"mendel",
	"mendeleev",
	"meitner",
	"meninsky",
	"merkle",
	"mestorf",
	"mirzakhani",
	"montalcini",
	"moore",
	"morse",
	"murdock",
	"moser",
	"napier",
	"nash",
	"neumann",
	"newton",
	"nightingale",
	"nobel",
	"noether",
	"northcutt",
	"noyce",
	"panini",
	"pare",
	"pascal",
	"pasteur",
	"payne",
	"perlman",
	"pike",
	"poincare",
	"poitras",
	"proskuriakova",
	"ptolemy",
	"raman",
	"ramanujan",
	"ride",
	"ritchie",
	"rhodes",
	"robinson",
	"roentgen",
	"rosalind",
	"rubin",
	"saha",
	"sammet",
	"sanderson",
	"satoshi",
	"shamir",
	"shannon",
	"shaw",
	"shirley",
	"shockley",
	"shtern",
	"sinoussi",
	"snyder",
	"solomon",
	"spence",
	"stonebraker",
	"sutherland",
	"swanson",
	"swartz",
	"swirles",
	"taussig",
	"tereshkova",
	"tesla",
	"tharp",
	"thompson",
	"torvalds",
	"tu",
	"turing",
	"varahamihira",
	"vaughan",
	"villani",
	"visvesvaraya",
	"volhard",
	"wescoff",
	"wilbur",
	"wiles",
	"williams",
	"williamson",
	"wilson",
	"wing",
	"wozniak",
	"wright",
	"wu",
	"yalow",
	"yonath",
	"zhukovsky",
	]
	_person_name = random.choice(first_name).title() + '_' + random.choice(last_name).title()
	return _person_name
